# Change these first
owner: AnotiaWang # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: 博客
    url: https://blog.ataw.top
  - name: 域名根页面
    url: https://www.ataw.top
  - name: 阿里云盘资源站点
    url: https://ar.ataw.top
  - name: Animenz 曲谱网
    url: https://animenz.ataw.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ataw.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Anotia 网页服务监控
  introTitle: "基于 Upptime.js 的自动化服务监控"
  introMessage: 此页面展示 Anotia 的网页服务在线状况。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/AnotiaWang
    - title: Blog
      href: https://blog.ataw.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
